#!/bin/sh
## Auto-reload script for development

which entr || echo "You need to have entr installed" || exit 1

SRC=src
DEST=dest
SITENAME=Demo
SITEURL=http://localhost:5000
HTTPCMD="nix run nixos.httplz -c httplz dest"

$(sleep 1 && $HTTPCMD) &!

while :
do
  find . -type f ! -path '*/.*' |
  entr -d ./n3sg.sh $SRC $DEST $SITENAME $SITEURL
done
